services:
  web:
    image: fastapi-app-image
    build:
      context: .
      dockerfile: Dockerfile

    container_name: test-server

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - .:/app

    restart: always