"""real_neon_setup

Revision ID: 866e2bad7f35
Revises: 
Create Date: 2026-07-09 19:13:00.110172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '866e2bad7f35'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model',
    sa.Column('modelID', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('modelID')
    )
    op.create_index(op.f('ix_ai_model_modelID'), 'ai_model', ['modelID'], unique=False)
    op.create_table('inputs',
    sa.Column('inputID', sa.Integer(), nullable=False),
    sa.Column('input_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('inputID')
    )
    op.create_index(op.f('ix_inputs_inputID'), 'inputs', ['inputID'], unique=False)
    op.create_table('outputs',
    sa.Column('outputID', sa.Integer(), nullable=False),
    sa.Column('output_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('outputID')
    )
    op.create_index(op.f('ix_outputs_outputID'), 'outputs', ['outputID'], unique=False)
    op.create_table('users',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('subscription', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('user_name')
    )
    op.create_index(op.f('ix_users_userID'), 'users', ['userID'], unique=False)
    op.create_table('requests',
    sa.Column('requestID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('modelID', sa.Integer(), nullable=True),
    sa.Column('inputID', sa.Integer(), nullable=True),
    sa.Column('outputID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inputID'], ['inputs.inputID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modelID'], ['ai_model.modelID'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outputID'], ['outputs.outputID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('requestID')
    )
    op.create_index(op.f('ix_requests_requestID'), 'requests', ['requestID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_requestID'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_users_userID'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_outputs_outputID'), table_name='outputs')
    op.drop_table('outputs')
    op.drop_index(op.f('ix_inputs_inputID'), table_name='inputs')
    op.drop_table('inputs')
    op.drop_index(op.f('ix_ai_model_modelID'), table_name='ai_model')
    op.drop_table('ai_model')
    # ### end Alembic commands ###
